"""add_enhanced_performance_metrics

Revision ID: 170821aa5594
Revises: 
Create Date: 2024-11-03 04:36:39.928079+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '170821aa5594'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_init')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_user_name', table_name='users')
    op.drop_table('users')
    op.add_column('server_performance', sa.Column('authenticated_connections', sa.Integer(), nullable=False))
    op.add_column('server_performance', sa.Column('anonymous_connections', sa.Integer(), nullable=False))
    op.add_column('server_performance', sa.Column('avg_connection_duration', sa.Float(), nullable=False))
    op.add_column('server_performance', sa.Column('unique_ips', sa.Integer(), nullable=False))
    op.add_column('server_performance', sa.Column('endpoint_stats', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_performance', 'endpoint_stats')
    op.drop_column('server_performance', 'unique_ips')
    op.drop_column('server_performance', 'avg_connection_duration')
    op.drop_column('server_performance', 'anonymous_connections')
    op.drop_column('server_performance', 'authenticated_connections')
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('hashed_password', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('status', mysql.ENUM('ACTIVE', 'INACTIVE', 'PENDING'), nullable=False),
    sa.Column('roles', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('reset_token', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('reset_token_expiry', mysql.DATETIME(), nullable=True),
    sa.Column('last_passwords', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_user_name', 'users', ['user_name'], unique=True)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('db_init',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('initialized_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
